### ISSUE TITLE
Larger genomes than E coli -- and getting started.

### ISSUE THREAD

**Issue by JohnUrban** [fxia22/HINGE#47]
Hi,

This is an exciting tool. Thanks for developing it.

Have you tried it on genomes larger than Ecoli yet?

I have a 300 Mb insect genomewith 40-50X long read coverage and would like to try it.

Any tips or recommendations appreciated.

best,

 John

**Comment by govinda-kamath** [comment]
Hi John,

Thanks for the kind words.

We have tried this on  _C. elegans_ which is around 220Mb. HINGE can work on your dataset as long as you have something like 50-100 Gb RAM. 

One aspect we've not handled yet is the centromere/telomeres. We're thinking about the right algorithm to attack these. For a temporary fix, I think we just will just throw away reads corresponding to telomeres (we should be able to do this in a few days). 

The default parameters should work in this case. And you should obtain chromosomes long chromosomes which are connected at the end with telomeres. 

Please keep us posted in case you run into trouble (or success).  We'd be interested in any feedback.

Thanks,
Govinda.

**Comment by govinda-kamath** [comment]
BTW, we just modified the code to delete the reads from the telomeric regions. Just set

```del_telomere = 1;```

to the ini file.

**Comment by JohnUrban** [comment]
Hi Govinda,

Thanks for getting back to me. I am yet to run HINGE -- it is on a big TODO list -- but anticipate running it in the coming week.

What are the pros and cons of ```del_telomere = 1;``` ?

best,

  John

**Comment by JohnUrban** [comment]
Oh nevermind about the del_telomere thing - I see you mentioned it in your first response.

**Comment by JohnUrban** [comment]
Hi Govinda,

Just a note -- I had to change this in all the python files:
#!/usr/bin/python
to
#!/usr/bin/env python

for them to work.

It might be good to change them in your code as the latter will figure out the correct location of python on anyone's system.

best,

 John

**Comment by govinda-kamath** [comment]
Thanks John for letting us know. I've fixed it.

**Comment by JohnUrban** [comment]
Hi again Govinda,

Just another note -- not sure what usually happens for other people, but in order to be able to call all the python files I had to give them permission:
chmod u+x file.py

e.g.
Before
```
-rw-r--r-- 1 jurban sgerbi 4.1K Jul 26 10:30 /gpfs_home/jurban/software/hinge/HINGE/scripts/unitig.py
```
After:
```
-rwxr--r-- 1 jurban sgerbi 4.1K Jul 26 10:30 /gpfs_home/jurban/software/hinge/HINGE/scripts/unitig.py
```

Also I cannot seem to locate seqtk ... where is that? or is that from another program?

best,

  John

**Comment by JohnUrban** [comment]
I am guessing it is Heng Li's:
https://github.com/lh3/seqtk

?

**Comment by fxia22** [comment]
@JohnUrban Yes, we are using seqtk to convert from fastq to fasta.

**Comment by JohnUrban** [comment]
Hi Govinda,

is this the expected result for the Ecoli data?
Consensus0	4633810
Consensus1	4635442
Consensus2	12262
Consensus3	11246

Are 0 and 1 basically revcomps of each other?
Same Q for 2 and 3....


best,

  John

**Comment by ilanshom** [comment]
Hi John,

Yes, that's correct. From the point of view of an assembly graph, we believe that representing both a contig and its reverse complement is the way to go. While in this simple case of E. coli this may seem redundant, representing the reverse complements as separate nodes on the graph allows you to easily identify when there is a long inverted repeat in the genome, because the two strands merge on the graph. 

I'm not sure what the small contig (2 and 3) is, maybe some nodes we pruned out of the graph but didn't properly delete.

ilan

**Comment by JohnUrban** [comment]
Thanks ilan.
Those seems to be good reasons to do it that way. On the other hand, from my perspective, I also just need an assembly with each contig represented once for downstream analyses. For example, even just calculating size statistics as NG50 to be able to compare with other assemblies -- or for various reference-free evaluations (e.g. LAP, ALE, FRCbam, REAPR). Is it safe to say that all the contigs come consecutively in pairs? For example, (0,1) (2,3) (4,5), etc. If so, then I suppose it could be trivial to select just one of each. If not, is there any way to get just one of each?

best,

  John

**Comment by ilanshom** [comment]
John, thanks again for another helpful comment. 

The current implementation doesn't guarantee that the reverse complements will come in consecutive pairs. So we will add an option to the get_draft script (something like --norevcomp) to only produce one contig per each of these pairs. This should make the output more useful for the downstream analysis you are interested in.

I'll let you know when this is done.

**Comment by JohnUrban** [comment]
Many thanks ilan.

**Comment by JohnUrban** [comment]
Hi @ilanshom -- any chance you could give me an idea of when that option will be available for the get_draft script?

**Comment by ilanshom** [comment]
We got a bit caught up with some other stuff, but we should be able to have it done tonight. Sorry for the delay

**Comment by JohnUrban** [comment]
No problem at all. Just trying to plan my week a bit. Thanks for getting back to me.

**Comment by ilanshom** [comment]
Hi John,

The current get_draft_path.py script outputs (besides the edges.list file used in the remainder of the pipeline) a file named ecoli_nonrevcomp.fasta with a list of the contigs with no reverse complemented pairs. These are not error-corrected yet, but they should allow you to run some downstream analysis. Also, the script uses pbcore (https://pypi.python.org/pypi/pbcore/1.2.1).

To error-correct them, you would need to run the consensus pipeline on ecoli_nonrevcomp.fasta (instead of ecoli.draft.fasta). We'll work on getting these instructions into the readme and perhaps on adding a python wrapper that runs the whole pipeline.

Best,

ilan

**Comment by JohnUrban** [comment]
Thank you.

To be sure I am clear, in the ecoli pipeline:
```
get_draft_path.py $PWD ecoli ecolidemo.G2.graphml
```
...will now output ```ecoli_nonrevcomp.fasta ``` in addition to other things.
Do I then run:
```
draft_assembly --db ecoli --las ecoli.las --prefix ecoli --config <path-to-nominal.ini> --out ecoli_nonrevcomp
```
... or something similar?


Does get_draft_path.py also output ```ecoli.draft.fasta``` ?

I suppose the consensus steps for the nonrevcomp draft would look something like this:
```
correct_head.py ecoli.draft.fasta ecoli.draft.pb.fasta draft_map.txt
fasta2DB draft ecoli.draft.pb.fasta 
HPCmapper draft ecoli | zsh -v  
LAmerge draft.ecoli.las draft.ecoli.*.las
consensus draft ecoli draft.ecoli.las ecoli.consensus.fasta utils/nominal.ini
get_consensus_gfa.py <working directory> ecoli ecoli<identifier-of-run>.G2.graphml ecoli.consensus.fasta
```
But with some changes -- e.g. ecoli.draft.fasta would be ecoli_nonrevcomp.fasta.

If you have a moment, writing up the pipeline for ecoli_nonrevcomp.fasta would be helpful. There are things I am unsure of -- for example, whether draft_map.txt would change....

Ultimately, I'd like to have revcomp-containing (e.g. for visualization/reasons you mention) and nonrevcomp assemblies (for treating like a normal assembly).

A single python script wrapping over everything would definitely be welcome. Either way, I am wondering if there are changes anywhere in the pipeline I should make for a 300 Mb eukaryotic genome. Falcon for example, seems to require a fair amount of messing around for the Daligner options. If you are familiar with the Falcon pipeline, I have something like this in fc_run.cfg:
```
pa_DBsplit_option = -a -x500 -s200
pa_HPCdaligner_option = -v -B128 -e0.70 -M24 -l1000 -s100

ovlp_DBsplit_option = -x500 -s200
ovlp_HPCdaligner_option = -v -B128 -e.96 -M16 -l500 -s100
```

For the ecoli pipeline, DBsplit seems fine (almost the same):
```
DBsplit -x500 -s100 ecoli 
```

On the other hand, the HPCdaligner options are probably different. Will that matter much?
Also, I suppose the HPCdaligner commands lend themselves to distributing the jobs across multiple nodes (as done by Falcon). Is there any support for this planned? I am curious how long it will take if done serially... (I am yet to run this on the actual real data -- only ecoli so far)...

Ok -- I am done brain streaming and dumping questions on you. Thanks for everything.

**Comment by ilanshom** [comment]
Hi John,

I just added two wrapper scripts to HINGE/scripts called pipeline_consensus.py and pipeline_consensus_norevcomp.py. The first one runs the consensus pipeline currently described on the readme to generate the double-stranded graphs, and the second one produces just a fasta file (ecoli_nonrevcomp.consensus.fasta) with a non-reverse-complemented list of contigs.

They can be run as:

pipeline_consensus.py ecoli path-to-nominal.ini demo

and

pipeline_consensus_norevcomp.py ecoli path-to-nominal.ini demo

This assumes that you've done the alignment and assembly steps of the pipeline, so that the folder contains ecoli.db, ecoli.las (and some hidden files like .ecoli.idx), ecolidemo.G2.graphml, and a log subfolder.

Regarding your questions about the DAligner configurations, Falcon needs to change them because it runs DAligner twice, and with different purposes each time (once in the error-correction step, and once in the assembly step). We do the assembly directly on the error-prone reads, so daligner's default options seem to work well. So I don't see a very clear reason to play with the parameters at this point. We haven't done much testing on something like a 300Mbp eukaryotic genome, but I would be concerned about ploidy, telomeres, centromeres, etc, more than the running time itself. 

ilan

**Comment by govinda-kamath** [comment]
Just to add to Ilan's comment on DAligner, the `-e0.70 -l1000` is the default DAligner parameters for Pacbio type data with 15% error rates.  The `-M` is the memory restriction, and the `-B` is the number of blocks aligned to each other at a time (this is mainly used for scheduling). In our case, our run of DAligner is basically the same as the first run of DAligner in FALCON as far as the quality of the alignment is concerned.  (I've not really played with the `-B` parameter, and this is one avenue where one could potentially obtain savings on timing.) 

FALCON's second run of DAligner is for much smaller nominal error rates of their P-reads (around 2%) and hence have completely different settings.

**Comment by JohnUrban** [comment]
Thank you both for your insightful responses. 

I will try to get a run through started today and will let you know how it goes.

**Comment by ilanshom** [comment]
John, just wanted to let you know that we recently fixed some issues with the consensus module and with the two consensus pipelines that we had previously added. I would recommend updating your files and rebuilding.

**Comment by JohnUrban** [comment]
Thanks Ilan. Re-installing now.

**Comment by ilanshom** [comment]
John, one more comment. We've recently created an analysis pipeline as an ipython notebook, which we hope can make it easier for people to run the pipeline. It's in a separate [repository](https://github.com/govinda-kamath/HINGE-analyses). Let me know if you have any comments/suggestions.

**Comment by JohnUrban** [comment]
Thanks for being so helpful.

**Comment by JohnUrban** [comment]
Based on your new consensus pipeline scripts, is it safe to say that the protocol in the README can now be executed as such (notice I only changed lines after ```# get consensus assembly```):

```
source utils/setup.sh
mkdir data/ecoli
cd data/ecoli
# reads.fasta should be in data/ecoli
fasta2DB ecoli reads.fasta
DBsplit -x500 -s100 ecoli     
HPCdaligner -t5 ecoli | csh -v
# alternatively, you can put output of HPCdaligner to a bash file and edit it to support 
rm ecoli.*.ecoli.*
LAmerge ecoli.las ecoli.+([[:digit:]]).las
rm ecoli.*.las # we only need ecoli.las
DASqv -c100 ecoli ecoli.las

# Run filter

mkdir log
Reads_filter --db ecoli --las ecoli.las -x ecoli --config <path-to-nominal.ini>

# Run layout

hinging --db ecoli --las ecoli.las -x ecoli --config <path-to-nominal.ini> -o ecoli

# Run postprocessing

python pruning_and_clipping.py ecoli.edges.hinges ecoli.hinge.list <identifier-of-run>


# get draft assembly 

get_draft_path.py <working directory> ecoli ecoli<identifier-of-run>.G2.graphml
draft_assembly --db ecoli --las ecoli.las --prefix ecoli --config <path-to-nominal.ini> --out ecoli.draft


# get consensus assembly

pipeline_consensus.py ecoli path-to-nominal.ini demo
pipeline_consensus_norevcomp.py ecoli path-to-nominal.ini demo

```

**Comment by govinda-kamath** [comment]
Yes. You need to run only one of the two scripts. 

```
pipeline_consensus.py ecoli path-to-nominal.ini demo
```

to get the double stranded GFA.


```
pipeline_consensus_norevcomp.py ecoli path-to-nominal.ini demo
```

to get one-stranded contigs.

**Comment by JohnUrban** [comment]
Got it. Thanks.
I will run both to get both I suppose.

**Comment by JohnUrban** [comment]
Not sure if it matters to you, but I had to do ```chmod u+x``` for both ```pipeline_consensus.py``` and ```pipeline_consensus_norevcomp.py```

**Comment by JohnUrban** [comment]
Oh and a question -- am I correct in saying that ```get_draft_path.py``` no longer outputs ```ecoli_nonrevcomp.fasta``` ?

**Comment by JohnUrban** [comment]
Hi again -- I also needed to change the first line in those consensus pipeline python scripts to:

```#!/usr/bin/env python```

**Comment by govinda-kamath** [comment]
Thanks John. We missed that on the header. I've fixed it. 

And yes. `get_draft_path.py` no longer outputs `ecoli_nonrevcomp.fasta`.

**Comment by JohnUrban** [comment]
Regarding the protocol question above -- it looks like the following lines are actually not necessary since they are run in the consensus pipeline:
```
# get draft assembly 

get_draft_path.py <working directory> ecoli ecoli<identifier-of-run>.G2.graphml
draft_assembly --db ecoli --las ecoli.las --prefix ecoli --config <path-to-nominal.ini> --out ecoli.draft
```

**Comment by JohnUrban** [comment]
For ```HPCdaligner -t5 ecoli``` -- would you recommend -t5 for a 300 Mb genome?

**Comment by JohnUrban** [comment]
I will probably just leave that option off for my first run through.

**Comment by JohnUrban** [comment]
I began a Falcon to get through the daligner steps that seem to be shared with HINGE. The data/files that falcon is populates the 0-rawreads directory with should be sufficient to start somewhere later in the HINGE pipeline, correct?

I need to do this to take advantage of its parallelization, otherwise the HPCdaligner step in HINGE will take forever and ever. The blocks of daligner/LAsort/etc commands need to be massively parallelized. I am working on a python wrapper script to attempt to do that for SLURM -- to include in my HINGE pipeline. However, I figured -- what the heck - Falcon already does this well. Why not just try making use of the daligner output in 0-rawreads?

So if you are familiar with Falcon, could you recommend how to use the daligner stuff in the 0-rawreads folder in the HINGE pipeline?

If helpful for discussion, my cfg file looks like this -- I tried to ensure the Falcon wrappers use all reads as that seems to be what is intended by HINGE:
```
[General]

use_tmpdir = false 

job_type = slurm

input_fofn = input.fofn

input_type = raw

	
# The length cutoff used for seed reads used for initial mapping
####################
##### CHANGED THIS FROM -1 to 1 FOR HINGE
###################
length_cutoff = 1
genome_size = 292000000

# The length cutoff used for seed reads usef for pre-assembly (>0, was not able to do -1)
####################
##### CHANGED THIS FROM 500 to 1 FOR HINGE -- though it likely doesnt use this...
###################
length_cutoff_pr = 1

## For SGE.... might not need for slurm (but it did not hurt with lambda, etc)
jobqueue = production


#Pre-Assembly 
sge_option_da = --cpus-per-task 8 --mem 30g --time 48:000:00 --qos=ccmb-condo
sge_option_la = --cpus-per-task 2 --mem 30g --time 48:00:00 --qos=ccmb-condo
pa_DBsplit_option = -a -x500 -s200

### all are defaults like HINGE wants -- except I have -B128, -M24, and -v here. 
pa_HPCdaligner_option = -v -B128 -e0.70 -M24 -l1000 -s100
pa_concurrent_jobs = 1000


### FOR HINGE, NOTHING MATTERS AFTER THIS LINE ####
#consensus for error correction
sge_option_cns = --cpus-per-task 8 --mem 60g --time 48:00:00 --qos=ccmb-condo
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
cns_concurrent_jobs = 1000


## overlap detection for assembly
sge_option_pda = --cpus-per-task 8 --mem 30g --time 48:00:00 --qos=ccmb-condo
sge_option_pla = --cpus-per-task 2 --mem 30g --time 48:00:00 --qos=ccmb-condo
ovlp_concurrent_jobs = 1000
ovlp_DBsplit_option = -x500 -s200
ovlp_HPCdaligner_option = -v -B128 -e.96 -M16 -l500 -s100

# overlap filtering
overlap_filtering_setting = --max_diff 40 --max_cov 80 --min_cov 2 --n_core 12


sge_option_fc = --cpus-per-task 16 --mem 30g --time 48:00:00 --qos=ccmb-condo
```

**Comment by JohnUrban** [comment]
p.s.
I tried HINGE with the default protocol first:
```
correct_head.py reads.fasta reads.pb.fasta map.txt
DB=sciara
fasta2DB $DB reads.pb.fasta
DBsplit -x500 -s100 $DB
HPCdaligner $DB > hpcdaligner.txt
bash -v hpcdaligner.txt
rm ${DB}.*.${DB}.*.las
LAmerge ${DB}.las ${DB}.[[:digit:]]*.las
DASqv -c100 ${DB} ${DB}.las
mkdir log
Reads_filter --db ${DB} --las ${DB}.las -x ${DB} --config nominal.ini
hinging --db ${DB} --las ${DB}.las -x ${DB} --config nominal.ini -o ${DB}
pruning_and_clipping.py ${DB}.edges.hinges ${DB}.hinge.list demo
pipeline_consensus.py ${DB} nominal.ini demo
pipeline_consensus_norevcomp.py ${DB} nominal.ini demo
```
It had a fair amount of segmentation faults at the daligner steps...
e.g.
```
daligner sciara.1 sciara.1
daligner sciara.2 sciara.1 sciara.2
daligner sciara.3 sciara.1 sciara.2 sciara.3
hpcdaligner.txt: line 4: 21451 Segmentation fault      daligner sciara.3 sciara.1 sciara.2 sciara.3
```

There was >160GB RAM available for this run and 4 threads (I could always allot more of each -- not sure where the threads are being used in the pipeline though). slurm seems to say that the job only used up to 13GB of RAM at its peak though.

I canceled the run due to the segmentation faults and b/c it was clear that the HPCdaligner commands would take for ever running linearly one after the other....

Since I have had success with daligner in the Falcon pipeline in terms of both parallelization and no seg faults -- I figured I'd try to get the daligner steps done that way.

**Comment by ilanshom** [comment]
Hi John,

Thank for all the comments and suggestions.

Regarding the consensus pipeline, you're correct that those two commands are included in the consensus wrappers. But so are all the other commands related to the consensus. So if you are calling pipeline_consensus.py (as you are above), then you don't need to include any other consensus-related command.

Regarding -t5, my understanding is that this is useful in the case where the genome has very repetitive regions, as it prevents the number of matching k-mers from being too large and using too much memory. But if you are using the -M parameter (by doing things as Falcon does) then I believe -t shouldn't be set (at least that's what Myers suggests).

Are you using the latest version of DAligner? It seems that some of these seg faults have been fixed. In any case, I like your idea of getting the alignments from the DAligner run of Falcon. I believe all you would have to do is to take all the *.[0-9].las files from inside the 0-rawreads folder, and then start the pipeline you have above from the LAmerge command. 

Govinda, Fei, let me know if I'm missing something here.

ilan

**Comment by JohnUrban** [comment]
Thanks @ilanshom 

To be clear -- let me know if there is anything redundant in the following:
```
source utils/setup.sh
mkdir data/ecoli
cd data/ecoli
# reads.fasta should be in data/ecoli
fasta2DB ecoli reads.fasta
DBsplit -x500 -s100 ecoli     
HPCdaligner -t5 ecoli | csh -v
# alternatively, you can put output of HPCdaligner to a bash file and edit it to support 
rm ecoli.*.ecoli.*
LAmerge ecoli.las ecoli.+([[:digit:]]).las
rm ecoli.*.las # we only need ecoli.las
DASqv -c100 ecoli ecoli.las

# Run filter

mkdir log
Reads_filter --db ecoli --las ecoli.las -x ecoli --config <path-to-nominal.ini>

# Run layout

hinging --db ecoli --las ecoli.las -x ecoli --config <path-to-nominal.ini> -o ecoli

# Run postprocessing

python pruning_and_clipping.py ecoli.edges.hinges ecoli.hinge.list <identifier-of-run>


# get draft and consensus assembly

pipeline_consensus.py ecoli path-to-nominal.ini demo
pipeline_consensus_norevcomp.py ecoli path-to-nominal.ini demo
```

**Comment by JohnUrban** [comment]
RE: segfault and daligner version
For the HINGE steps, I use the daligner stuff that is downloaded during the following hinge download/install protocol:
```
module load git
module load gcc/4.9.2
module load boost/1.55.0
module load hdf5/1.8.14
module load cmake/3.6.0

git clone https://github.com/fxia22/HINGE.git
cd HINGE
git submodule init
git submodule update
pwd=$PWD
cd $pwd/thirdparty/DAZZ_DB
make -j 8
cd $pwd/thirdparty//DALIGNER
make -j 8
cd $pwd/thirdparty/DASCRUBBER
make -j 8
cd $pwd/thirdparty/DEXTRACTOR
make -j 8
cd $pwd
mkdir build
cd $pwd/build
cmake .. -DCMAKE_C_COMPILER=/gpfs/runtime/opt/gcc/4.9.2/bin/gcc -DCMAKE_CXX_COMPILER=/gpfs/runtime/opt/gcc/4.9.2/bin/g++
make -j 8
```

Now that I'm looking at it, can you tell me what the effects of ```-j 8``` are... ?

If I use the dalgner stuff with falcon, I similarly use what I download and install with falcon... probably the same versions.

**Comment by JohnUrban** [comment]
RE: getting started with the daligner results from falcon's 0-rawreads

There are 3 types of subdirectories in 0-rawreads:
(i) job_xxxx/
(ii) m_xxxx/
(iii) preads/

In my case, there seem to be 65 of each type of job_ and m_ subdir.

It looks like the job dirs have daligner jobs and results. For example in ```job_0000/``` there is a file called ```rj_0000.sub.sh```. It contains lines like:
```
daligner -v -H1 -e0.7 -M24 raw_reads.57 raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4 raw_reads.5 raw_reads.6 raw_reads.7 raw_reads.8 raw_reads.9 raw_reads.10 raw_reads.11 raw_reads.12 raw_reads.13 raw_reads.14 raw_reads.15 raw_reads.16 raw_reads.17 raw_reads.18 raw_reads.19 raw_reads.20 raw_reads.21 raw_reads.22 raw_reads.23 raw_reads.24 raw_reads.25 raw_reads.26 raw_reads.27 raw_reads.28 raw_reads.29 raw_reads.30 raw_reads.31 raw_reads.32 raw_reads.33 raw_reads.34 raw_reads.35 raw_reads.36 raw_reads.37 raw_reads.38 raw_reads.39 raw_reads.40 raw_reads.41 raw_reads.42 raw_reads.43 raw_reads.44 raw_reads.45 raw_reads.46 raw_reads.47 raw_reads.48 raw_reads.49 raw_reads.50 raw_reads.51 raw_reads.52 raw_reads.53 raw_reads.54 raw_reads.55 raw_reads.56 raw_reads.57
set +e
LAcheck -v raw_reads *.las
set -e
LAsort -v raw_reads.1.raw_reads.57.C0 raw_reads.1.raw_reads.57.N0 raw_reads.1.raw_reads.57.C1 raw_reads.1.raw_reads.57.N1 raw_reads.1.raw_reads.57.C2 raw_reads.1.raw_reads.57.N2 raw_reads.1.raw_reads.57.C3 raw_reads.1.raw_reads.57.N3 && LAmerge -v L1.1.57 raw_reads.1.raw_reads.57.C0.S raw_reads.1.raw_reads.57.N0.S raw_reads.1.raw_reads.57.C1.S raw_reads.1.raw_reads.57.N1.S raw_reads.1.raw_reads.57.C2.S raw_reads.1.raw_reads.57.N2.S raw_reads.1.raw_reads.57.C3.S raw_reads.1.raw_reads.57.N3.S
LAsort -v raw_reads.2.raw_reads.57.C0 raw_reads.2.raw_reads.57.N0 raw_reads.2.raw_reads.57.C1 raw_reads.2.raw_reads.57.N1 raw_reads.2.raw_reads.57.C2 raw_reads.2.raw_reads.57.N2 raw_reads.2.raw_reads.57.C3 raw_reads.2.raw_reads.57.N3 && LAmerge -v L1.2.57 raw_reads.2.raw_reads.57.C0.S raw_reads.2.raw_reads.57.N0.S raw_reads.2.raw_reads.57.C1.S raw_reads.2.raw_reads.57.N1.S raw_reads.2.raw_reads.57.C2.S raw_reads.2.raw_reads.57.N2.S raw_reads.2.raw_reads.57.C3.S raw_reads.2.raw_reads.57.N3.S
.
.
.
..
set +e
LAcheck -vS raw_reads L1.1.57
set -e
set +e
LAcheck -vS raw_reads L1.2.57
set -e
set +e
LAcheck -vS raw_reads L1.3.57
set -e
set +e
LAcheck -vS raw_reads L1.4.57
set -e
set +e
LAcheck -vS raw_reads L1.5.57
.
.
.
rm -f *.C?.las *.C?.S.las
rm -f *.N?.las *.N?.S.las
```
It looks like the output of those are many .las files.


It looks like the m_xxxx dirs are for LAmerge. For example, ```m_00001``` has a file called ```m_00001/rp_00001.sub.sh ```, which contains the following lines:
```
#!/bin/bash
set -vex
LAmerge -v raw_reads.1 L1.1.1 L1.1.2 L1.1.3 L1.1.4 L1.1.5 L1.1.6 L1.1.7 L1.1.8 L1.1.9 L1.1.10 L1.1.11 L1.1.12 L1.1.13 L1.1.14 L1.1.15 L1.1.16 L1.1.17 L1.1.18 L1.1.19 L1.1.20 L1.1.21 L1.1.22 L1.1.23 L1.1.24 L1.1.25 L1.1.26 L1.1.27 L1.1.28 L1.1.29 L1.1.30 L1.1.31 L1.1.32 L1.1.33 L1.1.34 L1.1.35 L1.1.36 L1.1.37 L1.1.38 L1.1.39 L1.1.40 L1.1.41 L1.1.42 L1.1.43 L1.1.44 L1.1.45 L1.1.46 L1.1.47 L1.1.48 L1.1.49 L1.1.50 L1.1.51 L1.1.52 L1.1.53 L1.1.54 L1.1.55 L1.1.56 L1.1.57 L1.1.58 L1.1.59 L1.1.60 L1.1.61 L1.1.62 L1.1.63 L1.1.64 L1.1.65
```
The .las files from the job subdirs seem to be symlinked into the m_ subdirs.
My guess is the output in the m subdirs is a single file in each called ```raw_reads.x.las```. For example in m_00001/ there is ```raw_reads.1.las```.

Each of these merged las files is then used in the preads subdirectory with ```LA4Falcon``` to pipe into ```fc_consensus``` and ultimately output a fasta file -- 65 in total.


#############################################################
Would the merged las files in the m_xxxx dirs be useful?
Or should I just start with all the las files in the job_xxxx dirs

For example:
````
LAmerge merged.las job_*/*.las
```

Or:
```
LAmerge merged.las m_*/*.las
```

Or does it not matter....?

**Comment by ilanshom** [comment]
RE: sequence of commands

Everything in your pipeline looks right, and there are no redundant steps. Just notice that "demo" in the final two steps should be the same thing as <identifier-of-run> used in pruning_and_clipping.

RE: segfault and daligner version

We just use -j 8 to run make in 8 parallel jobs. I don't think this is very important. 
Also, you may need to run `git submodule sync` and `git submodule update --init --recursive` to make sure that you get the latest DAligner.


RE: getting started with the daligner results from falcon's 0-rawreads

I believe you can ignore the smaller .las files in the m_xxxx files and just use the raw_reads.*.las files. Actually, when we run Falcon, we get soft links to all of them in the 0-rawreads folder, so we can just do

```LAmerge merged.las raw_reads.*.las```

or, equivalently,

```LAmerge merged.las m_*/*.las```

**Comment by JohnUrban** [comment]
Thanks for your helpful response as usual.

I was thinking that ```LAmerge merged.las job_*/*.las``` might be better than ```LAmerge merged.las m_*/*.las``` since the m_xxxx dirs have the las files from the job_xxxx dirs symlinked in them as well as the merged las files. Perhaps ```LAmerge merged.las m_*/raw_reads.*.las``` to only merge the merged las files in the m_xxxx dirs would be good too.

I may be able to get HINGE running on the las files tonight -- will let you know how it goes.

**Comment by JohnUrban** [comment]
Would using ```0-rawreads/raw_reads.db``` be the right thing for the following:

```
DASqv -c100 0-rawreads/raw_reads merged.las

mkdir log
Reads_filter --db 0-rawreads/raw_reads --las merged.las -x ecoli --config <path-to-nominal.ini>

# Run layout

hinging --db 0-rawreads/raw_reads --las merged.las -x ecoli --config <path-to-nominal.ini> -o ecoli

```

That is what I have running for the moment...

**Comment by ilanshom** [comment]
Hm, now I'm a bit confused about all these .las files. I believe just merging the raw_reads.*.las should be enough, but I could be wrong. I'll try to look into that a little more carefully.

And regarding the db, you are correct. You should use the raw_reads.db database in 0-rawreads. Let us know how things go!

**Comment by JohnUrban** [comment]
In this command:
``` pipeline_consensus.py ecoli path-to-nominal.ini demo```

What is "ecoli"?
e.g. does it point to the fasta2DB database...?
or something else?

**Comment by ilanshom** [comment]
The command assumes that in the current directory you have 

```ecoli.db (and accompanying hidden files like .ecoli.idx, created by fasta2DB) 
ecoli.las
ecolidemo.G2.graphml```

**Comment by JohnUrban** [comment]
I am curious how do guys were able to do the 220 Mbp C elegans genome with just 50-100GB RAM. 
Even 250 GB RAM has not been enough for me to get past the Reads_filter step for a 300 Mb genome with ~16 Gbp of reads (~55x cov). Right now it is running with 512 GB RAM and the slurm process that monitors says it is using more than that -- so it will be killed any moment now I suspect. That is pretty much the most I am able to throw at it. Unfortunately, this run is just a subset of the data -- I have 10-20x more coverage I left out that would be ideal to include. 

Any thoughts on how this was possible for C elegans? 

I suppose I will be unable to use HINGE further until there is a solution to its memory needs, either on my side or yours. Would it be possible to apply ```Reads_filter``` to subsets of reads? For example, in the 0-raw_reads falcon directory, they are already broken up into subsets -- e.g. the raw_reads.x.las file in the m_xxxx directories. 

I should say that I am given the impression that ```hinging``` will have similar memory problems since it also seems to use the entire DB and gigantic merged las file (343 GB in my case).

Thanks for your support. Hopefully, we can figure something out. I am eager to see how HINGE deals with repeats in my genome-of-interest.


p.s. I just looked and ```Reads_filter``` was indeed killed for exceeding 512 GB RAM.

**Comment by govinda-kamath** [comment]
Hi John,

Both `Reads_filter` and `hinging` load the entire las file into memory. In the case of _C. elegans_ the las file we had was something like 80 GB. Handling a las file of 343 GB may work on 512 GB RAM, but we'll have to rethink our input protocol to allow handling such huge las files.

**Comment by ilanshom** [comment]
Hi John,

Thanks for your efforts and feedback. It really helps us deciding how to move forward. Sorry we didn't foresee this issue with the loading of the large .las file.

The main memory bottleneck for HINGE is indeed the way we handle the .las file. So even if we have a larger genome (like in the case of C. elegans), if the coverage depth is not very large, or if you choose the DAligner parameters to be more stringent, you can end up with .las file that can be entirely loaded into memory.

You may want to try running DAligner increasing -h and -l. By default, -l (the minimum overlap length) is 1000, so you may want to try 2000 or 3000. The parameter -h controls how the fraction of the overlap that should be covered by common k-mers for DAligner to find it. A good rule of thumb is to choose -h to be 0.03 times the value of -l. 

But of course all this is just a (potential) quick fix, and would affect the quality of your assembly as you would be relying on a higher coverage. The right thing to do is to modify the way HINGE handles the loading of the overlaps so that larger genomes can be assembled. We are working on this, but it's not a simple change to make. We'll keep you updated on that.

Thanks again,

ilan

**Comment by JohnUrban** [comment]
Hi ilan and govinda,

Thanks for getting back to me.

It is totally okay that this isn't working first try, and I am happy if your developments go in a direction that enables me to use HINGE. If anything, I should apologize for continuously raising issues. I feel like a nuisance.

Thanks for the DAligner tips. I may try some of those changes and/or feeding it a subset of the reads longer than some cutoff (to lower the depth). Ultimately, I do not want to short-change HINGE if I compare its performance to other assemblers though. I will keep you updated on whatever I do regarding HINGE.
