### ISSUE TITLE
Working on larger genomes (errors, questions and discussions)

### ISSUE THREAD

**Issue by danshu** [fxia22/HINGE#48]
Hi,

I'm working on a larger genome (200-300Mb) with high repeat content. I'm really excited when I find HINGE. 

The first error I had is "Pacbio header line name inconsisten", which should be because that I used a merged.fasta with pacbio data from different cells to build the DB, as was explained here (https://github.com/thegenemyers/DEXTRACTOR/issues/4)
Then how can I build the DB with fasta2DB using pacbio data from multiple pacbio cells?

Another question is about the -t parameter of HPCdaligner. In the Ecoli example, -t5 was used. If I got it correctly, "-t  any k-mer that occurs more than t times in either the subject or target is not counted in the heuristic". So should I modify this -t value for a highly repeative genome?

Thanks,
Quan

**Comment by danshu** [comment]
Hi @fxia22,

Thanks for your quick reply. I will try to solve it following your suggestions.

Thanks,
Quan

**Comment by danshu** [comment]
@fxia22  I solved this problem by running " python correct_head.py input.fasta output.fasta map.txt". Thanks again for your help.
By the way, can I ask whether there is a detailed manual for HINGE, including those scripts? Actually I have to read the "correct_head.py" file to know how to use it...  If there is a detailed manual, it will be of great help!

Cheers,
Quan

**Comment by fxia22** [comment]
Thank you for your feedback @danshu, sure, we will write a manual about how to use it.

**Comment by danshu** [comment]
Hi @fxia22,
After funning HPCdaligner, there is a step "rm ecoli.*.ecoli.*" right before "LAmerge ecoli.las ecoli.*.las".
However, what I have after running HPCdaligner are something like "ecoli.4.ecoli.2.N2.las". 
So is there anything wrong with my results from HPCdaligner?

Thanks,
Quan

**Comment by govinda-kamath** [comment]
Hi Quan,

These are internal .las that Daligner sets up. We do not use these. The DAligner code itself merges these if you look at the script generated by HPCdaligner.

Best,
G.

**Comment by danshu** [comment]
Hi @govinda-kamath 
Sorry that I may not explain it clearly. I'm just following the demo run for assembling the ecoli genome.
"...
HPCdaligner -t5 ecoli | csh -v
# alternatively, you can put output of HPCdaligner to a bash file and edit it to support 
rm ecoli.*.ecoli.*
LAmerge ecoli.las ecoli.*.las
rm ecoli.*.las # we only need ecoli.las
..."
Because the output files from "HPCdaligner -t5 ecoli | csh -v" are something like "ecoli.4.ecoli.2.N2.las", I may delete all these files if I follow "rm ecoli.*.ecoli.*".  I may skip this "rm ecoli.*.ecoli.*" step to get ecoli.las but I just don't know if there is something wrong with my HPCdaligner run. 
And which is the script generated by HPCdaligner?

Thanks,
Quan

**Comment by govinda-kamath** [comment]
Hi Quan,

One obtains files of the form  
- ecoli.[1-7].ecoli.[1-7].C[0-3].las  
- ecoli.[1-7].ecoli.[1-7].N[0-3].las  
- ecoli.[1-7].las  
Only files of the last type are merged to obtain ecoli.las. The files of the first two types are spit out by Daligner as intermediate files. You can delete them as well after the LAmerge.

**Comment by danshu** [comment]
Hi Govinda,

Thanks and this is exactly what I want to know. And actually I can't find "ecoli.[1-7].las" files in the working directory.

**Comment by govinda-kamath** [comment]
Hi Quan,

I'm not sure what went wrong there. Can you try removing all .las files and rerun Daligner (and post what is printed out if it does not work)?

**Comment by danshu** [comment]
@govinda-kamath I'm rerunning Daligner now. I will post what is printed out when it finishes.
