### ISSUE TITLE
Binary release of HINGE

### ISSUE THREAD

**Issue by HuangYukun** [fxia22/HINGE#57]
Hi,
The software seems really interesting and I want to try it on my own datasets. Due to unsuccessful trials of compiling the software, may I ask for a binary release to run directly? Thanks.

Jimmy

**Comment by ilanshom** [comment]
Hi Jimmy, we currently don't have a binary that works across all linux distributions, but we will try to generate one. I'll let you know when this is done.

**Comment by HuangYukun** [comment]
@ilanshom Thanks for the reply. In fact I am able to compile and run HINGE now. Will come to you for help if there're any problems.

**Comment by HuangYukun** [comment]
Hi,
I have tried several datasets through the pipeline but some of them stuck in the command ```get_draft_path.py <working directory> ecoli ecoli<identifier-of-run>.G2.graphml``` with error messages like this

**Comment by govinda-kamath** [comment]
Hi Jimmy, 

Are these datasets public? This error seems to be some read not being in the database (I may be mistaken though.)

**Comment by HuangYukun** [comment]
Hi @govinda-kamath,
I don't know if I understand you correctly but the datasets are from ourselves and they can pass all previous steps until get_draft_path.py

**Comment by govinda-kamath** [comment]
Hi Jimmy,

We haven't been able to reproduce that error here. Would it be possible for you to send us the *.G2.graphml that creates the error for us to debug that? The graphml file doesn't contain the sequence information, so you wouldn't be sharing any data (in case that's a concern for you).

Thanks,
Govinda.

**Comment by HuangYukun** [comment]
@govinda-kamath Thanks for the kind reply. I am glad to send you the *.G2.graphml. How can we start?

**Comment by HuangYukun** [comment]
I may also provide the data source however it would take some time. Thanks again.

**Comment by govinda-kamath** [comment]
Thanks Jimmy.

Can you send the *.G2.graphml to gkamath@stanford.edu and ilan.shomorony@berkeley.edu?

Thanks again for helping us improve the software,
Govinda.

**Comment by HuangYukun** [comment]
The dataset is sent to your email. Thanks.

Best,
Jimmy

**Comment by govinda-kamath** [comment]
Thanks a ton.

Govinda.

**Comment by govinda-kamath** [comment]
Seems to work with the latest HINGE release.
