### ISSUE TITLE
Hints for parametrization

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [fxia22/HINGE#62]
We have a bact. with nasty 35-40kb repeats. The genome is about 6.8Mb in size. The four SMRTcells we sequenced give about 3 Gb of raw data.

Do you have some hints for the parametrization in nominal.ini and also for Gene M. tools?

I would go for more strict qual. parameters (lower values are more strict, right? :-) ) and maybe filter for longer reads. Would you agree and if yes which values? What else would you suggest?

We have a quite powerfull machine, so we don't mind to trade high qual. for high comp. demands.

Thx!

**Comment by govinda-kamath** [comment]
Hi,

The default values should work here (assuming the repeats are not repeated tandem repeats as like in telomeres). 

Filtering for longer reads may not be necessary. Higher coverage with shorter reads do help HINGE to detect chimeric reads, and annotate long reads for being at the start/end of repeats. 

Let us know how it goes.

Thanks,
Govinda.
