### ISSUE TITLE
Question: Which graph did you print for the biorxiv preprint

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [fxia22/HINGE#63]
When I run Hinge I get different graph files. What is the meaning of the different graphs?

Which one did you print with Gephi for the publication / which one do you suggest?

**Comment by ilanshom** [comment]
The *.G2s.graphml shows the two strands separately, while *.G2c.graphml (which is the one we used for the biorxiv preprint) has the two strands combined. The other graphs are before the pruning and clipping operations.

When you open it in Gephi you will need to use ForceAtlas2 to generate a nice layout. Alternatively, you can see what we did to generate the figures on an ipython notebook that is available [here](https://github.com/govinda-kamath/HINGE-analyses). In the notebook we also explain how we color the graphs on the preprint according to the contigs produced by hgap.

**Comment by MichaelsGITIGIT** [comment]
Thanks a lot
