### ISSUE TITLE
Detailed explanation of parameters in nominal.ini

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [fxia22/HINGE#69]
Maybe I missed that. But I have trouble to find the definition of **all** parameters in `nominal.ini` and the connection to where they are mentioned in the paper?

Is there a document describing it in detail? I would be awesome if you can give a doc which describes the parameters!

Many thanks!

**Comment by ilanshom** [comment]
@MichaelsGITIGIT, we added the file [parameter_description](../blob/master/parameter_description.md) with the list of all parameters listed by HINGE. Are there specific parameters for which you need a more detailed explanation?

**Comment by MichaelsGITIGIT** [comment]
Many thanks! I will get back to you if I need more clarification on one parameter. But I guess other people are also happy about the parameter description you provide.

I observe this in general for algorithmic papers; There is a nice description of the algorithm and a nice implementation. But the link between the description of the algorithm and an explanation where the parameters fit into the picture lacks. Sure, one could dig through the code. But this takes quite some time. So there should be a standard/consensus on how to do that :-)
