### ISSUE TITLE
Key and Assertion errors in get_draft_path_norevcomp.py

### ISSUE THREAD

**Issue by alimayy** [fxia22/HINGE#71]
Hi guys,

In one of the datasets I'm working on, when I use  the `get_draft_path.py` it works just fine but when I replace it with `get_draft_path_norevcomp.py` I get a key error. I had a look at it but couldn't figure out quickly what it's about, though it seems like a mapping issue. Perhaps you can have a look at it? I'm attaching the relevant files.

Thanks in advance
[r2s2r2s2_run_id.G2.zip](https://github.com/fxia22/HINGE/files/482333/r2s2r2s2_run_id.G2.zip)

```
get_draft_path_norevcomp.py ./ r2s2 r2s2r2s2_run_id.G2.graphml
Traceback (most recent call last):
  File "~/packages/HINGE/scripts/get_draft_path_norevcomp.py", line 316, in <module>
    RCmap[path_to_vert[path]] = path_to_vert[path_to_search]
KeyError: '20549_1'
```

Edit:
The same script gives an Assertion Error with another dataset. Attaching the file for that dataset here too.

[r2s3r2s3_run_id.G2.zip](https://github.com/fxia22/HINGE/files/482354/r2s3r2s3_run_id.G2.zip)

```
get_draft_path_norevcomp.py ./ r2s3 r2s3r2s3_run_id.G2.graphml
Traceback (most recent call last):
  File ~/packages/HINGE/scripts/get_draft_path_norevcomp.py", line 125, in <module>
    segment = get_string(path_var)
  File "~/packages/HINGE/scripts/get_draft_path_norevcomp.py", line 44, in get_string
    assert itm[1][0] >= itm[1][1]
AssertionError
```

**Comment by govinda-kamath** [comment]
Hi @alimayy,

We plan to make `get_draft_path_norevcomp.py` redundant and get the one directed fastas directly. We'll get back to you on this in a day or two.

**Comment by govinda-kamath** [comment]
We've  fixed the norevcomp in the `dev` branch. For ecoli, we have put in a demo file to get the no reverse complement file. Let us know if there are any issues there.

**Comment by alimayy** [comment]
I just cloned and compiled the dev branch. Now I get the following error when I use `draft_assembly`:

`draft_assembly: /home/amay/packages/HINGE-dev/src/consensus/draft.cpp:643: int draft_assembly_ctg(std::vector<std::tuple<Node, Node, int> >&, LAInterface&, std::vector<LOverlap*>&, std::unordered_map<int, std::vector<LOverlap*> >&, std::unordered_map<int, std::unordered_map<int, std::vector<LOverlap*> > >&, std::vector<Read*>&, int, int, int, int, int, bool, std::string&): Assertion `cut_end <= contig.size()' failed.`

Any ideas? Can I help with debugging (the sequences aren't public)?

**Comment by fxia22** [comment]
Hi @alimayy , we added some output, can you run your experiment with the latest commit in master branch again and attach the output? 

Thanks!

**Comment by alimayy** [comment]
Hi @fxia22 and @govinda-kamath, I've cloned and built the new master. When I use it on two datasets, in one of them it successfully finishes, and in the other one it fails with the same error. stderr and stdout files from both datasets are attached. Hope this helps!
[draft_assembly_stderr_stdout.zip](https://github.com/fxia22/HINGE/files/499163/draft_assembly_stderr_stdout.zip)

**Comment by fxia22** [comment]
Hi @alimayy , don't worry about "Read indices out of range", it doesn't affect the results. 

We made some change to address the problem at draft assembly, can you check it that works? 

Thanks,
Fei

**Comment by alimayy** [comment]
Hi @fxia22 I still have problems with draft assembly. See below. Can I provide you with something?

```
ctg size:7196cut_start:3364cut_end:7678
draft_assembly: /mnt/nfs/programs/HINGE-dev/src/consensus/draft.cpp:678: int draft_assembly_ctg(std::vector<std::tuple<Node, Node, int> >&, LAInterface&,                               std::vector<LOverlap*>&, std::unordered_map<int, std::vector<LOverlap*> >&, std::unordered_map<int, std::unordered_map<int, std::vector<LOverlap*> > >&, s                              td::vector<Read*>&, int, int, int, int, int, bool, bool, std::string&): Assertion `cut_end <= contig.size()' failed.

draft_assembly --db 0017_rev --las 0017_rev.las --prefix 0017_rev --config /mnt/nfs/programs/HINGE-dev/utils/nominal.ini --out 0017_rev.draft did not prod                              uce a return code of 0, quiting!

```

**Comment by fxia22** [comment]
Hi @alimayy, sorry about that, can you provide the full output of `draft_assembly`, thanks!

**Comment by alimayy** [comment]
Sure, I didn't direct the output for this one, so I'm attaching the terminal output (stderr and stdout mixed). And because it's copy pasted from the terminal there are a few long spaces here and there. Let me know if you need the .err and .out separately
[draft_assembly_stderr_stdout.txt](https://github.com/fxia22/HINGE/files/543806/draft_assembly_stderr_stdout.txt)
!

**Comment by fxia22** [comment]
It's fine, I will handle that. Thanks!

**Comment by alimayy** [comment]
Thanks! Looking forward to this being resolved. I've bumped into this in maybe two or three datasets.

**Comment by alimayy** [comment]
Hi @fxia22, I'm attaching the stderr and stdout of another Sequel dataset that I've experienced this issue with. This time the species of interest is a 30 MB fungi. 
[0017_hinge_asmbly_b24_11.err.txt](https://github.com/fxia22/HINGE/files/611846/0017_hinge_asmbly_b24_11.err.txt)
[0017_hinge_asmbly_b24_11.out.txt](https://github.com/fxia22/HINGE/files/611845/0017_hinge_asmbly_b24_11.out.txt)

**Comment by fxia22** [comment]
@alimayy you still have that issue using `dev` branch?

**Comment by alimayy** [comment]
Yes, this is dev
