### ISSUE TITLE
get_consensus_gfa.py error

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [fxia22/HINGE#75]
After you having resolved #65 I get an error at last step (get_consensus_gfa.py):

```
user@myMachine:~/HINGE_all$ get_consensus_gfa.py $PWD pk pkid.G2.graphml pk.consensus.fasta 
Traceback (most recent call last):
  File "/home/bioinf/Software/HINGE/scripts/get_consensus_gfa.py", line 62, in <module>
    nodes_to_keep = [x for x in g.nodes() if consensus_contigs[g.node[x]['contig_id']] != '' ]
KeyError: 'contig_id'
```

**AND** I don't know what this means exactly and if it is related to this problem - HPC.daligner gives me after successful run:

```
...
# Check level 2 .las files jobs (1) (optional but recommended)
LAcheck -vS draft pk draft.pk
  **pk: Read indices out of range
  draft.pk: Read indices out of range**
# Remove level 1 .las files
rm L1.1.1.las L1.1.2.las L1.1. ...
```

**Comment by govinda-kamath** [comment]
Hi @MichaelsGITIGIT, 

Can you give us the `pkid.G2.graphml` and `draft_map.txt`? Neither of these have any sequence information.

**Comment by MichaelsGITIGIT** [comment]
Here you go ...

[draft_map.txt](https://github.com/fxia22/HINGE/files/497503/draft_map.txt)

[pkid.G2.zip](https://github.com/fxia22/HINGE/files/497504/pkid.G2.zip)

**Comment by govinda-kamath** [comment]
It looks like the problem here is with `pkid_draft.graphml`. Could you give us that? It also contains no sequence information.

**Comment by MichaelsGITIGIT** [comment]
Working on it :-)

**Comment by govinda-kamath** [comment]
@ilanshom has fixed this in the latest version. Let us know if the problem persists!
