### ISSUE TITLE
Python KeyError in get_consensus_gfa.py

### ISSUE THREAD

**Issue by emilhaegglund** [fxia22/HINGE#79]
Following the instructions in the README but using nanopore reads. Made it to the last step where I get this error.
```
Traceback (most recent call last):
  File "get_consensus_gfa.py", line 62, in <module>
    nodes_to_keep = [x for x in g.nodes() if consensus_contigs[g.node[x]['contig_id']] != '' ]
KeyError: 'contig_id'
```

**Comment by govinda-kamath** [comment]
Can you give us the `draft_map.txt`, `<name>_draft.graphml`, and `<name>.G2.graphml` files? These contain no sequence information in case that's a concern.

**Comment by emilhaegglund** [comment]
The files are in the zip-folder.
[issue_files.zip](https://github.com/fxia22/HINGE/files/526982/issue_files.zip)

**Comment by govinda-kamath** [comment]
@ilanshom  has fixed this in the latest version. Let us know if the problem persists!

**Comment by emilhaegglund** [comment]
Worked with the latest version.
