### ISSUE TITLE
RSII as input

### ISSUE THREAD

**Issue by mictadlo** [fxia22/HINGE#91]
Hi,
One SMRT cell contains on h5 file, but when we converted it to Fasta file we get 3 Fasta files.

Can we combine these 3 Fasta files and import them to `fasta2DB` or do they have to be imported separately? 

Thank you in advance

Michal

**Comment by govinda-kamath** [comment]
You can add them to the db using `fasta2DB` repeatedly or merge the files using a script like the following:
```
#!/usr/bin/env python
#usage: python merge_fastas.py list-of-fasta-files output.fasta

import sys
from pbcore.io import FastaIO

fasta_file_list = sys.argv[1]
out_fasta_file = sys.argv[2]
writer = FastaIO.FastaWriter(out_fasta_file)

with open(fasta_file_list,'r') as f:
    for iname in f:
        reader = FastaIO.FastaReader(iname)
        for i,record in enumerate(reader):
            writer.writeRecord(record.header, record.sequence)
```

**Comment by mictadlo** [comment]
Thank you it works.
